Repository PaddlePaddle/PaddleScience, pull requests merged in 2023-10, with the labels that each got.

#575 modify laplace2d to hydra style
  docs/zh/examples/laplace2d.md
  examples/laplace/conf/laplace2d.yaml
  examples/laplace/laplace2d.py
Labels: contributor

#579 hydra 改造 phylstm
  docs/zh/examples/phylstm.md
  examples/phylstm/conf/phylstm2.yaml
  examples/phylstm/conf/phylstm3.yaml
  examples/phylstm/phylstm2.py
  examples/phylstm/phylstm3.py
Labels: contributor

#536 赛题十五：PIRBN 子目录 1D_sine_function
  docs/zh/examples/pirbn.md
  jointContribution/PIRBN/README.md
  jointContribution/PIRBN/analytical_solution.py
  jointContribution/PIRBN/jacobian_function.py
  jointContribution/PIRBN/main.py
  jointContribution/PIRBN/pirbn.py
  jointContribution/PIRBN/rbn_net.py
  jointContribution/PIRBN/train.py
  mkdocs.yml
Labels: contributor, HappyOpenSource Pro

#581 【hydra No.20】改造 bubble
  docs/zh/examples/bubble.md
  examples/bubble/bubble.py
  examples/bubble/conf/bubble.yaml
Labels: contributor, HappyOpenSource

#560 【Hackathon 5th No.56】A Physics-Informed Neural Network to solve 2D steady-state heat equation
  docs/zh/examples/heat_pinn.md
  examples/Heat_PINN/fdm.py
  examples/Heat_PINN/heat_pinn.py
  mkdocs.yml
Labels: contributor, PaddlePaddle Hackathon

#582 【hydra No.11】for hpinns model
  docs/zh/examples/hpinns.md
  examples/hpinns/conf/hpinns.yaml
  examples/hpinns/holography.py
Labels: contributor, HappyOpenSource

#600 [Enhance] add retain_graph/create_graph options for jacobian and hessian
  examples/bubble/bubble.py
  ppsci/autodiff/ad.py
Labels: contributor

#591 【hydra No.10】labelfree_DNN_surrogate
  docs/zh/examples/labelfree_DNN_surrogate.md
  examples/pipe/conf/poiseuille_flow.yaml
  examples/pipe/poiseuille_flow.py
Labels: contributor

#598 [Doc] add example table
  README.md
  docs/index.md
  docs/zh/examples/cylinder2d_unsteady.md
  docs/zh/overview.md
  mkdocs.yml
  ppsci/visualize/plot.py
  ppsci/visualize/vtu.py
Labels: contributor

#589 【hydra No.15】deeponet
  docs/zh/examples/deeponet.md
  examples/operator_learning/conf/deeponet.yaml
  examples/operator_learning/deeponet.py
Labels: contributor

#599 【hydra No.8】Adapt ldc2d_steady_Re10 to hydra
  docs/zh/examples/ldc2d_steady.md
  examples/ldc/conf/ldc2d_steady_Re10.yaml
  examples/ldc/ldc2d_steady_Re10.py
Labels: contributor

#583 【hydra No.18】Adapt DeepCFD to hydra
  docs/zh/examples/deepcfd.md
  examples/deepcfd/conf/deepcfd.yaml
  examples/deepcfd/deepcfd.py
Labels: contributor, HappyOpenSource

#590 【hydra No.9】darcy2d
  docs/zh/examples/darcy2d.md
  examples/darcy/conf/darcy2d.yaml
  examples/darcy/darcy2d.py
Labels: contributor, HappyOpenSource

#601 Bugfix nosampler
  ppsci/data/__init__.py
Labels: contributor

#592 【hydra No.17】tempoGAN
  docs/zh/examples/tempoGAN.md
  examples/tempoGAN/conf/tempogan.yaml
  examples/tempoGAN/tempoGAN.py
Labels: contributor, HappyOpenSource

#603 【hydra No.12】deephpms
  docs/zh/examples/deephpms.md
  examples/deephpms/burgers.py
  examples/deephpms/conf/burgers.yaml
  examples/deephpms/conf/korteweg_de_vries.yaml
  examples/deephpms/conf/kuramoto_sivashinsky.yaml
  examples/deephpms/conf/navier_stokes.yaml
  examples/deephpms/conf/schrodinger.yaml
  examples/deephpms/korteweg_de_vries.py
  examples/deephpms/kuramoto_sivashinsky.py
  examples/deephpms/navier_stokes.py
  examples/deephpms/schrodinger.py
Labels: contributor, HappyOpenSource

#604 [Fix] Fix code block type in document
  README.md
  docs/index.md
  docs/zh/examples/amgnet.md
  docs/zh/examples/bracket.md
  docs/zh/examples/bubble.md
  docs/zh/examples/hpinns.md
  docs/zh/examples/laplace2d.md
  docs/zh/examples/ldc2d_unsteady.md
  docs/zh/examples/phylstm.md
Labels: contributor

#608 [Fix] use Assign with fp64 in XPINNs
  jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
  ppsci/optimizer/lr_scheduler.py
Labels: contributor
