Repository PaddlePaddle/PaddleScience, pull requests merged in 2023-12, with the labels that each got.

#678 【benchmark】fix gpu_mem unit
  ppsci/solver/printer.py
Labels: contributor

#701 【PPSCI Doc No.76】
  ppsci/loss/l1.py
Labels: contributor

#699 【Hackathon 5th No.62】GraphCast: Learning skillful medium-range global weather forecasting
  jointContribution/graphcast/README.md
  jointContribution/graphcast/args.py
  jointContribution/graphcast/config/GraphCast.json
  jointContribution/graphcast/config/GraphCast_operational.json
  jointContribution/graphcast/config/GraphCast_small.json
  jointContribution/graphcast/data/dataset/.gitkeep
  jointContribution/graphcast/data/graphcast-jax2paddle.csv
  jointContribution/graphcast/data/params/.gitkeep
  jointContribution/graphcast/data/stats/.gitkeep
  jointContribution/graphcast/data/template_graph/.gitkeep
  jointContribution/graphcast/datasets.py
  jointContribution/graphcast/graphcast.py
  jointContribution/graphcast/graphtype.py
  jointContribution/graphcast/run.py
  jointContribution/graphcast/utils.py
  jointContribution/graphcast/vis.py
Labels: PaddlePaddle Hackathon

#687 【PPSCI Doc No.1】ppsci.data.process.transform.CropData
  ppsci/data/process/transform/preprocess.py
Labels: contributor, HappyOpenSource

#691 【PPSCI Doc No.8】ppsci.data.dataset.ERA5SampledDataset
  ppsci/data/dataset/era5_dataset.py
Labels: contributor, HappyOpenSource

#703 【PPSCI Doc No.75, 77-85】
  ppsci/loss/func.py
  ppsci/loss/integral.py
  ppsci/loss/l1.py
  ppsci/loss/l2.py
  ppsci/loss/mae.py
  ppsci/loss/mse.py
Labels: contributor, HappyOpenSource

#688 【PPSCI Doc No.2-7】ppsci.data.process.transform
  ppsci/data/process/transform/preprocess.py
Labels: contributor, HappyOpenSource

#720 【快乐开源】迁移 CFDGCN 案例至 PaddleScience
  docs/zh/examples/cfdgcn.md
  ppsci/arch/cfdgcn.py
Labels: contributor, HappyOpenSource

#723 【PPSCI Doc No.86-92】
  ppsci/metric/func.py
  ppsci/metric/l2_rel.py
  ppsci/metric/mae.py
  ppsci/metric/mse.py
  ppsci/metric/rmse.py
  ppsci/solver/solver.py
Labels: contributor

#724 【PPSCI Doc No.10、11、30】
  ppsci/arch/cfdgcn.py
  ppsci/arch/unetex.py
  ppsci/data/dataset/airfoil_dataset.py
  ppsci/data/dataset/cylinder_dataset.py
Labels: contributor, HappyOpenSource
