Repository PaddlePaddle/PaddleScience, pull requests merged in 2023-09, with the labels that each got.

#511 PaddleScience 论文复现 Deep learning based denoising process
  jointContribution/DU_CNN/.gitignore
  jointContribution/DU_CNN/README.md
  jointContribution/DU_CNN/config.yaml
  jointContribution/DU_CNN/data/Baseline.mat
  jointContribution/DU_CNN/data/poddata.mat
  jointContribution/DU_CNN/main.py
  jointContribution/DU_CNN/models/basicblock.py
  jointContribution/DU_CNN/models/network_model_batch.py
  jointContribution/DU_CNN/requirements.txt
  jointContribution/DU_CNN/utils/lr_scheduler.py
  jointContribution/DU_CNN/utils/mydataset.py
  jointContribution/DU_CNN/utils/pixelshuffle1d.py
  jointContribution/DU_CNN/utils/util.py
Labels: contributor, HappyOpenSource Pro

#523 【快乐开源】添加 HamiltonianMonteCarlo API
  ppsci/probability/__init__.py
  ppsci/probability/hmc.py
  test/probability/test_hmc.py
Labels: contributor, HappyOpenSource

#534 Docs
  docs/zh/api/probability.md
Labels: contributor, HappyOpenSource

#537 [Docs] fix incorrect validator param in DeepHPMs example
  examples/deephpms/burgers.py
  examples/deephpms/korteweg_de_vries.py
  examples/deephpms/kuramoto_sivashinsky.py
  examples/deephpms/navier_stokes.py
  examples/deephpms/schrodinger.py
Labels: contributor

#535 PaddleScience 论文复现 Extended Physics-Informed Neural Networks (XPINNs)
  jointContribution/XPINNs/README.md
  jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
  jointContribution/XPINNs/data/XPINN_2D_PoissonEqn.mat
  jointContribution/XPINNs/plotting.py
  jointContribution/XPINNs/requirements.txt
  ppsci/utils/initializer.py
Labels: contributor, HappyOpenSource Pro

#541 update HMC API
  ppsci/probability/hmc.py
  test/probability/test_hmc.py
  test/probability/test_hmc2.py
Labels: contributor, HappyOpenSource

#529 【快乐开源】迁移 DeepCFD 案例至 PaddleScience
  docs/zh/api/arch.md
  docs/zh/examples/deepcfd.md
  examples/deepcfd/deepcfd.py
  mkdocs.yml
  ppsci/arch/__init__.py
  ppsci/arch/unetex.py
Labels: contributor, HappyOpenSource

#540 复现 Phy-LSTM 论文
  docs/zh/api/arch.md
  docs/zh/examples/phylstm.md
  examples/phylstm/functions.py
  examples/phylstm/phylstm2.py
  examples/phylstm/phylstm3.py
  mkdocs.yml
  ppsci/arch/__init__.py
  ppsci/arch/phylstm.py
  ppsci/data/__init__.py
Labels: contributor, HappyOpenSource
