Repository PaddlePaddle/PaddleScience, pull requests merged in 2023-06, with the labels that each got.

#386 [add sdf] sphere
  ppsci/geometry/geometry_3d.py
Labels: contributor, status: proposed

#388 add unit test for normal_dot_vec
  test/equation/test_normal_dot_vec.py
Labels: contributor, status: proposed

#384 [add sdf] cuboid
  ppsci/geometry/geometry.py
  ppsci/geometry/geometry_3d.py
Labels: contributor, status: proposed

#391 [Feature] Add disk sdf_func
  ppsci/geometry/geometry_2d.py
  pyproject.toml
Labels: contributor, status: proposed

#387 [Feature] Add rectangle and triangle sdf_func
  ppsci/geometry/geometry_2d.py
Labels: contributor, status: proposed

#399 Update index.md
  docs/index.md
Labels: contributor, status: proposed

#400 add test for poisson
  test/equation/test_poisson.py
Labels: contributor, status: proposed

#397 Adding unittest for equation/pde/base.py
  test/equation/test_pde_base.py
Labels: contributor, status: proposed

#401 add unittest for viv
  test/equation/test_viv.py
Labels: contributor

#402 Fix typos
  examples/cylinder/2d_unsteady/transformer_physx/train_enn.py
  examples/cylinder/2d_unsteady/transformer_physx/train_transformer.py
  examples/deephpms/burgers.py
  examples/deephpms/korteweg_de_vries.py
  examples/deephpms/kuramoto_sivashinsky.py
  examples/deephpms/navier_stokes.py
  examples/deephpms/schrodinger.py
  examples/hpinns/functions.py
  examples/hpinns/holography.py
  examples/lorenz/train_enn.py
  examples/lorenz/train_transformer.py
  examples/rossler/train_enn.py
  examples/rossler/train_transformer.py
  ppsci/equation/pde/viv.py
  ppsci/geometry/geometry.py
  ppsci/geometry/timedomain.py
  ppsci/metric/func.py
  ppsci/optimizer/__init__.py
  ppsci/utils/download.py
  ppsci/utils/misc.py
  ppsci/utils/save_load.py
  ppsci/visualize/plot.py
Labels: contributor, status: proposed

#403 adding sdf_func to interval
  ppsci/geometry/geometry_1d.py
Labels: contributor, status: proposed

#394 add unit test for biharmonic
  test/equation/test_biharmonic.py
Labels: contributor, status: proposed, HappyOpenSource

#406 add Polygon sdf
  ppsci/geometry/geometry_2d.py
Labels: contributor
