Repository PaddlePaddle/PaddleScience, pull requests merged in 2023-11, with the labels that each got.

#607 【hydra No.4】aneurysm
  docs/zh/examples/aneurysm.md
  examples/aneurysm/aneurysm.py
  examples/aneurysm/conf/aneurysm.yaml
Labels: contributor

#602 【hydra No.13、14、16】lorenz/rossler/cylinder2d_unsteady_transformer_physx
  docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
  docs/zh/examples/lorenz.md
  docs/zh/examples/rossler.md
  examples/cylinder/2d_unsteady/transformer_physx/conf/enn.yaml
  examples/cylinder/2d_unsteady/transformer_physx/conf/transformer.yaml
  examples/cylinder/2d_unsteady/transformer_physx/train_enn.py
  examples/cylinder/2d_unsteady/transformer_physx/train_transformer.py
  examples/lorenz/conf/enn.yaml
  examples/lorenz/conf/transformer.yaml
  examples/lorenz/train_enn.py
  examples/lorenz/train_transformer.py
  examples/rossler/conf/enn.yaml
  examples/rossler/conf/transformer.yaml
  examples/rossler/train_enn.py
  examples/rossler/train_transformer.py
Labels: contributor, HappyOpenSource

#622 【hydra No.3】Adapt VIV to hydra
  docs/zh/examples/viv.md
  examples/fsi/conf/viv.yaml
  examples/fsi/viv.py
Labels: contributor, HappyOpenSource

#624 【hydra No.6】cylinder2d_unsteady
  docs/zh/examples/cylinder2d_unsteady.md
  examples/cylinder/2d_unsteady/conf/cylinder2d_unsteady.yaml
  examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
Labels: contributor, HappyOpenSource

#211 AI4S-论文复现-CFDGCN
  docs/zh/examples/cfdgcn.md
  jointContribution/CFDGCN/coarse.cfg
  jointContribution/CFDGCN/common.py
  jointContribution/CFDGCN/data.py
  jointContribution/CFDGCN/fine.cfg
  jointContribution/CFDGCN/main.py
  jointContribution/CFDGCN/mesh_utils.py
  jointContribution/CFDGCN/models.py
  jointContribution/CFDGCN/run.sh
  jointContribution/CFDGCN/su2paddle/su2_function.py
  jointContribution/CFDGCN/su2paddle/su2_function_mpi.py
  jointContribution/CFDGCN/su2paddle/su2_numpy.py
Labels: contributor, status: proposed

#630 PINO论文复现
  jointContribution/PINO/.gitmodules
  jointContribution/PINO/PINO_paddle/configs/operator/Re500-1_8-800-PINO-s.yaml
  jointContribution/PINO/PINO_paddle/configs/pretrain/Darcy-pretrain.yaml
  jointContribution/PINO/PINO_paddle/configs/pretrain/burgers-pretrain.yaml
  jointContribution/PINO/PINO_paddle/configs/test/burgers.yaml
  jointContribution/PINO/PINO_paddle/configs/test/darcy.yaml
  jointContribution/PINO/PINO_paddle/download_data.py
  jointContribution/PINO/PINO_paddle/eval_operator.py
  jointContribution/PINO/PINO_paddle/models/FCN.py
  jointContribution/PINO/PINO_paddle/models/FNO_blocks.py
  jointContribution/PINO/PINO_paddle/models/__init__.py
  jointContribution/PINO/PINO_paddle/models/basics.py
  jointContribution/PINO/PINO_paddle/models/fourier2d.py
  jointContribution/PINO/PINO_paddle/models/fourier3d.py
  jointContribution/PINO/PINO_paddle/models/utils.py
  jointContribution/PINO/PINO_paddle/prepare_data.py
  jointContribution/PINO/PINO_paddle/solver/random_fields.py
  jointContribution/PINO/PINO_paddle/train_burgers.py
  jointContribution/PINO/PINO_paddle/train_operator.py
  jointContribution/PINO/PINO_paddle/train_pino.py
  jointContribution/PINO/PINO_paddle/train_utils/__init__.py
  jointContribution/PINO/PINO_paddle/train_utils/datasets.py
  jointContribution/PINO/PINO_paddle/train_utils/eval_2d.py
  jointContribution/PINO/PINO_paddle/train_utils/eval_3d.py
  jointContribution/PINO/PINO_paddle/train_utils/losses.py
  jointContribution/PINO/PINO_paddle/train_utils/train_2d.py
  jointContribution/PINO/PINO_paddle/train_utils/train_3d.py
  jointContribution/PINO/PINO_paddle/train_utils/utils.py
  jointContribution/PINO/rfcs/PINO.md
  jointContribution/PINO/rfcs/figs/fig1.png
  jointContribution/PINO/rfcs/figs/fig2.png
Labels: contributor

#606 【Hackathon 5th No.58】 A physics-informed deep neural network for surrogate modeling in classical elasto-plasticity
  docs/zh/api/loss.md
  docs/zh/examples/epnn.md
  docs/zh/examples/epnn_images/loss_trend.png
  examples/epnn/conf/epnn.yaml
  examples/epnn/epnn.py
  examples/epnn/functions.py
  mkdocs.yml
  ppsci/arch/__init__.py
  ppsci/arch/epnn.py
  ppsci/loss/__init__.py
  ppsci/loss/mae.py
  ppsci/optimizer/lr_scheduler.py
  ppsci/utils/reader.py
Labels: contributor, PaddlePaddle Hackathon

#593 【Hackathon 5th No.61】Skillful nowcasting of extreme precipitation with NowcastNet
  docs/zh/api/arch.md
  docs/zh/api/data/dataset.md
  docs/zh/api/visualize.md
  docs/zh/examples/nowcastnet.md
  examples/nowcastnet/conf/nowcastnet.yaml
  examples/nowcastnet/nowcastnet.py
  mkdocs.yml
  ppsci/arch/__init__.py
  ppsci/arch/nowcastnet.py
  ppsci/data/dataset/__init__.py
  ppsci/data/dataset/radar_dataset.py
  ppsci/visualize/__init__.py
  ppsci/visualize/radar.py
  requirements.txt
Labels: contributor, PaddlePaddle Hackathon

#636 Fix EPNN
  docs/zh/examples/epnn.md
  ppsci/arch/epnn.py
Labels: contributor, PaddlePaddle Hackathon

#627 【hydra No.5】shock_wave
  docs/zh/examples/shock_wave.md
  examples/shock_wave/conf/shock_wave_Ma0.728.yaml
  examples/shock_wave/conf/shock_wave_Ma2.0.yaml
  examples/shock_wave/shock_wave.py
Labels: contributor, HappyOpenSource

#597 【Hackathon 5th No.57】Neural networks for topology optimization
  docs/zh/examples/topopt.md
  examples/topopt/conf/topopt.yaml
  examples/topopt/functions.py
  examples/topopt/topopt.py
  examples/topopt/topoptmodel.py
  mkdocs.yml
Labels: contributor, PaddlePaddle Hackathon
