Repository PaddlePaddle/PaddleScience, pull requests merged in 2024-05, with the labels that each got.

#875 【PPSCI Export&Infer No.15-16】
  docs/zh/examples/ldc2d_steady.md
  docs/zh/examples/ldc2d_unsteady.md
  examples/ldc/conf/ldc2d_steady_Re10.yaml
  examples/ldc/conf/ldc2d_unsteady_Re10.yaml
  examples/ldc/ldc2d_steady_Re10.py
  examples/ldc/ldc2d_unsteady_Re10.py
Labels: contributor, HappyOpenSource

#878 【PPSCI Export&Infer No.25】bracket
  docs/zh/examples/bracket.md
  examples/bracket/bracket.py
  examples/bracket/conf/bracket.yaml
Labels: contributor, HappyOpenSource

#883 【PPSCI Export&Infer No.11-12】
  docs/zh/examples/cylinder2d_unsteady.md
  docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
  examples/cylinder/2d_unsteady/conf/cylinder2d_unsteady_Re100.yaml
  examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
  examples/cylinder/2d_unsteady/transformer_physx/conf/transformer.yaml
  examples/cylinder/2d_unsteady/transformer_physx/train_transformer.py
  ppsci/arch/physx_transformer.py
Labels: contributor, HappyOpenSource

#884 【PPSCI Export&Infer No.21】tempoGAN
  docs/zh/examples/tempoGAN.md
  examples/tempoGAN/conf/tempogan.yaml
  examples/tempoGAN/tempoGAN.py
Labels: contributor, HappyOpenSource

#877 [Hackathon 6th Code Camp No.15] support earthformer docs
  docs/zh/examples/earthformer.md
  mkdocs.yml
  ppsci/data/dataset/sevir_dataset.py
Labels: contributor

#890 【PPSCI Export&Infer No.20】shock_wave
  docs/zh/examples/shock_wave.md
  examples/shock_wave/conf/shock_wave_Ma0.728.yaml
  examples/shock_wave/conf/shock_wave_Ma2.0.yaml
  examples/shock_wave/shock_wave.py
Labels: contributor

#887 【PPSCI Export&Infer No.9】Bubble
  docs/zh/examples/bubble.md
  examples/bubble/bubble.py
  examples/bubble/conf/bubble.yaml
Labels: contributor

#892 【PPSCI Export&Infer No.30】heat_exchanger
  docs/zh/examples/heat_exchanger.md
  examples/heat_exchanger/conf/heat_exchanger.yaml
  examples/heat_exchanger/heat_exchanger.py
Labels: contributor

#893 【PPSCI Export&Infer No.26-27】
  docs/zh/examples/control_arm.md
  examples/control_arm/conf/forward_analysis.yaml
  examples/control_arm/conf/inverse_parameter.yaml
  examples/control_arm/forward_analysis.py
  examples/control_arm/inverse_parameter.py
Labels: contributor

#900 【PPSCI Export&Infer No.13】 darcy2d
  docs/zh/examples/darcy2d.md
  examples/darcy/conf/darcy2d.yaml
  examples/darcy/darcy2d.py
Labels: contributor

#902 Add export & inference for hPINNs
  docs/zh/examples/hpinns.md
  examples/hpinns/conf/hpinns.yaml
  examples/hpinns/holography.py
Labels: contributor

#895 【PPSCI Export&Infer No.35】nowcastnet
  docs/zh/examples/nowcastnet.md
  examples/nowcastnet/conf/nowcastnet.yaml
  examples/nowcastnet/nowcastnet.py
  ppsci/arch/nowcastnet.py
Labels: contributor, HappyOpenSource

#867 [Hackathon 6th Code Camp No.15] support neuraloperator
  docs/zh/api/arch.md
  docs/zh/api/data/dataset.md
  examples/neuraloperator/conf/sfno_swe_pretrain.yaml
  examples/neuraloperator/conf/tfno_darcyflow_pretrain.yaml
  examples/neuraloperator/conf/uno_darcyflow_pretrain.yaml
  examples/neuraloperator/metric.py
  examples/neuraloperator/predictor.py
  examples/neuraloperator/train_sfno.py
  examples/neuraloperator/train_tfno.py
  examples/neuraloperator/train_uno.py
  ppsci/arch/__init__.py
  ppsci/arch/fno_block.py
  ppsci/arch/sfnonet.py
  ppsci/arch/tfnonet.py
  ppsci/arch/unonet.py
  ppsci/data/dataset/__init__.py
  ppsci/data/dataset/darcyflow_dataset.py
  ppsci/data/dataset/spherical_swe_dataset.py
  ppsci/paddle_harmonics/legendre.py
  ppsci/paddle_harmonics/quadrature.py
  ppsci/paddle_harmonics/random_fields.py
  ppsci/paddle_harmonics/sht.py
Labels: contributor

#879 Add allen cahn sota
  examples/allen_cahn/allen_cahn_defalut_ntk.py
  examples/allen_cahn/allen_cahn_sota.py
  examples/allen_cahn/conf/allen_cahn_defalut_ntk.yaml
  examples/allen_cahn/conf/allen_cahn_sota.yaml
  ppsci/arch/mlp.py
  ppsci/loss/mse.py
  ppsci/loss/mtl/__init__.py
  ppsci/loss/mtl/ntk.py
Labels: contributor

#849 【Hackathon 6th No.39】XPINN 迁移至 PaddleScience
  docs/zh/examples/xpinns.md
  examples/xpinn/conf/xpinn.yaml
  examples/xpinn/model.py
  examples/xpinn/plotting.py
  examples/xpinn/xpinn.py
Labels: contributor, PaddlePaddle Hackathon
