Repository PaddlePaddle/PaddleScience, pull requests merged in 2024-01, with the labels that each got.

#706 【Hackathon 5th No.60】 PhyGeoNet: Physics-Informed Geometry-Adaptive Convolutional Neural Networks for Solving Parameterized Steady-State PDEs on Irregular Domain
  docs/zh/api/arch.md
  docs/zh/examples/phygeonet.md
  examples/phygeonet/heat_equation/conf/conf.yaml
  examples/phygeonet/heat_equation/main.py
  examples/phygeonet/heat_equation_parameterized_BC/conf/conf.yaml
  examples/phygeonet/heat_equation_parameterized_BC/main.py
  mkdocs.yml
  ppsci/arch/__init__.py
  ppsci/arch/uscnn.py
Labels: contributor, PaddlePaddle Hackathon

#730 【PPSCI Doc No.93-96, 98-102】
  ppsci/utils/initializer.py
  ppsci/utils/misc.py
Labels: contributor, HappyOpenSource

#695 【Hackathon 5th No.53】NSFnets (Navier-Stokes Flow nets): Physics-informed neural networks for the incompressible Navier-Stokes equations
  docs/zh/examples/nsfnet.md
  examples/nsfnet/VP_NSFNet1.py
  examples/nsfnet/VP_NSFNet2.py
  examples/nsfnet/VP_NSFNet3.py
  examples/nsfnet/conf/VP_NSFNet1.yaml
  examples/nsfnet/conf/VP_NSFNet2.yaml
  examples/nsfnet/conf/VP_NSFNet3.yaml
  mkdocs.yml
Labels: contributor, PaddlePaddle Hackathon

#752 【PPSCI Doc No.12、13、14、15、16、17】ppsci.arch.Arch
  ppsci/arch/base.py
Labels: contributor, HappyOpenSource

#756 【PPSCI Doc No.20】ppsci.arch.DeepPhyLSTM
  ppsci/arch/phylstm.py
Labels: contributor

#758 【PPSCI Doc No.103】
  ppsci/utils/misc.py
Labels: contributor

#759 【PPSCI Doc No.104-105】
  ppsci/utils/save_load.py
Labels: contributor, HappyOpenSource

#674 【Hackathon 5th No.63】 PhyCRNet: Physics-informed Convolutional-Recurrent Network for Solving Spatiotemporal PDEs
  docs/zh/api/arch.md
  docs/zh/examples/phycrnet.md
  examples/phycrnet/conf/burgers_equations.yaml
  examples/phycrnet/conf/fitzhugh_nagumo_RD_equation.yaml
  examples/phycrnet/conf/lambda_omega_RD_equation.yaml
  examples/phycrnet/functions.py
  examples/phycrnet/main.py
  mkdocs.yml
  ppsci/arch/__init__.py
  ppsci/arch/phycrnet.py
Labels: contributor, PaddlePaddle Hackathon

#762 【PPSCI Doc No.106】update doc for `ppsci.visualize.save_vtu_from_dict`
  docs/zh/examples/bubble.md
  ppsci/visualize/vtu.py
Labels: contributor

#764 【PPSCI Doc No.108-109】update doc for `ppsci.visualize.save_plot_from_1d_dict` and `ppsci.visualize.save_plot_from_3d_dict`
  ppsci/visualize/plot.py
Labels: contributor

#765 remove python3.7 in docker
  docker/Dockerfile
  docker/run.sh
  docs/zh/install_setup.md
Labels: contributor, HappyOpenSource

#763 【PPSCI Doc No.107】update doc for `ppsci.visualize.save_vtu_to_mesh`
  ppsci/visualize/vtu.py
Labels: contributor, HappyOpenSource

#660 [Example] Add RegAE example
  docs/zh/api/arch.md
  docs/zh/examples/RegAE.md
  examples/RegAE/RegAE.py
  examples/RegAE/conf/RegAE.yaml
  examples/RegAE/dataloader.py
  ppsci/arch/__init__.py
  ppsci/arch/vae.py
  ppsci/loss/__init__.py
  ppsci/loss/kl.py
Labels: contributor

#670 【Hackathon 5th No.54】NSFnets (Navier-Stokes Flow nets): Physics-informed neural networks for the incompressible Navier-Stokes equations
  docs/zh/examples/nsfnet4.md
  examples/nsfnet/VP_NSFNet4.py
  examples/nsfnet/conf/VP_NSFNet4.yaml
  mkdocs.yml
Labels: contributor
