Repository PaddlePaddle/PaddleScience, pull requests merged in 2025-05, with the labels that each got.

#1149 Fix typos
  examples/allen_cahn/conf/allen_cahn_defalut_ntk.yaml
  examples/allen_cahn/conf/allen_cahn_sota.yaml
  examples/chip_heat/conf/chip_heat.yaml
  examples/fengwu/predict.py
  examples/fpde/conf/fractional_poisson_2d.yaml
  examples/graphcast/conf/graphcast_small.yaml
  examples/heart/conf/forward.yaml
  examples/heart/conf/inverse.yaml
  examples/heat_exchanger/conf/heat_exchanger.yaml
  examples/ifm/ifm.py
  examples/neuraloperator/conf/sfno_swe_pretrain.yaml
  examples/neuraloperator/conf/tfno_darcyflow_pretrain.yaml
  examples/neuraloperator/conf/uno_darcyflow_pretrain.yaml
  examples/nsfnet/VP_NSFNet1.py
  examples/nsfnet/VP_NSFNet2.py
  examples/nsfnet/VP_NSFNet3.py
  examples/nsfnet/VP_NSFNet4.py
  examples/pipe/poiseuille_flow.py
  examples/shock_wave/lhs.py
  examples/tempoGAN/tempoGAN.py
  examples/transformer4sr/functions_vis.py
  examples/transformer4sr/generate_datasets.py
  examples/xpinn/conf/xpinn.yaml
  jointContribution/gencast/conf/gencast.yaml
Labels: contributor, HappyOpenSource

#1150 Fix typos
  docs/zh/examples/drivaernetplusplus.md
  docs/zh/examples/phygeonet.md
  docs/zh/examples/tempoGAN.md
  examples/adr/README.md
  examples/moflow/optimize_moflow.py
  jointContribution/CFDGCN/mesh_utils.py
  jointContribution/PIRBN/README.md
  jointContribution/PIRBN/jacobian_function.py
  jointContribution/PIRBN/rbn_net.py
  jointContribution/graphcast/datasets.py
  ppsci/arch/afno.py
  ppsci/arch/cfdgcn.py
  ppsci/arch/cuboid_transformer.py
  ppsci/arch/cuboid_transformer_decoder.py
  ppsci/arch/extformer_moe_cuboid.py
  ppsci/arch/extformer_moe_cuboid_decoder.py
  ppsci/arch/fno_block.py
  ppsci/arch/geofno.py
  ppsci/arch/ifm_mlp.py
  ppsci/arch/mlp.py
  ppsci/arch/sfnonet.py
  ppsci/arch/tfnonet.py
  ppsci/arch/unonet.py
  ppsci/data/dataset/atmospheric_dataset.py
  ppsci/data/dataset/cgcnn_dataset.py
  ppsci/data/dataset/moflow_dataset.py
  ppsci/equation/pde/base.py
  ppsci/experimental/math_module.py
  ppsci/geometry/geometry.py
  ppsci/loss/mtl/agda.py
  ppsci/utils/__init__.py
  ppsci/utils/callbacks.py
  ppsci/utils/initializer.py
  ppsci/utils/logger.py
  ppsci/utils/save_load.py
  ppsci/utils/symbolic.py
  ppsci/utils/writer.py
  test/utils/test_ema.py
  test_tipc/README.MD
Labels: contributor

#1145 【Hackathon 8th No.17】FuXi 论文复现
  README.md
  docs/index.md
  docs/zh/examples/fuxi.md
  examples/fuxi/conf/fuxi.yaml
  examples/fuxi/conf/fuxi_long.yaml
  examples/fuxi/conf/fuxi_medium.yaml
  examples/fuxi/conf/fuxi_short.yaml
  examples/fuxi/predict.py
  examples/fuxi/requirements.txt
  examples/fuxi/util.py
  examples/fuxi/visualize.py
  mkdocs.yml
Labels: contributor, PaddlePaddle Hackathon

#1146 【Hackathon 8th No.23】Improved Training of Wasserstein GANs 论文复现
  examples/wgangp/conf/wgangp_cifar10.yaml
  examples/wgangp/conf/wgangp_mnist.yaml
  examples/wgangp/conf/wgangp_toy.yaml
  examples/wgangp/functions.py
  examples/wgangp/wgangp_cifar10.py
  examples/wgangp/wgangp_cifar10_model.py
  examples/wgangp/wgangp_mnist.py
  examples/wgangp/wgangp_mnist_model.py
  examples/wgangp/wgangp_toy.py
  examples/wgangp/wgangp_toy_model.py
Labels: contributor, PaddlePaddle Hackathon

#1152 【Hackathon 8th No.23】Improved Training of Wasserstein GANs 论文复现
  README.md
  docs/index.md
  docs/zh/examples/wgan_gp.md
  mkdocs.yml
Labels: contributor, PaddlePaddle Hackathon
